// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfpq2L9VEfOH1Ua8res62TmJ8aKOaN5wE',
    appId: '1:115332230968:web:fa2732305070a7e5a7dbcd',
    messagingSenderId: '115332230968',
    projectId: 'hw04-a0614',
    authDomain: 'hw04-a0614.firebaseapp.com',
    storageBucket: 'hw04-a0614.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTuyYeABmkWrhHojqpUr3aSjws0VApviQ',
    appId: '1:115332230968:android:893252ab8d8cb0c8a7dbcd',
    messagingSenderId: '115332230968',
    projectId: 'hw04-a0614',
    storageBucket: 'hw04-a0614.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5DxgRbpG8hMkS41GckcKuHDlXV8o4or0',
    appId: '1:115332230968:ios:cf04cf9553d51be5a7dbcd',
    messagingSenderId: '115332230968',
    projectId: 'hw04-a0614',
    storageBucket: 'hw04-a0614.firebasestorage.app',
    iosBundleId: 'com.example.hw04',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5DxgRbpG8hMkS41GckcKuHDlXV8o4or0',
    appId: '1:115332230968:ios:cf04cf9553d51be5a7dbcd',
    messagingSenderId: '115332230968',
    projectId: 'hw04-a0614',
    storageBucket: 'hw04-a0614.firebasestorage.app',
    iosBundleId: 'com.example.hw04',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfpq2L9VEfOH1Ua8res62TmJ8aKOaN5wE',
    appId: '1:115332230968:web:41632002a7b67a06a7dbcd',
    messagingSenderId: '115332230968',
    projectId: 'hw04-a0614',
    authDomain: 'hw04-a0614.firebaseapp.com',
    storageBucket: 'hw04-a0614.firebasestorage.app',
  );
}
